import 'reflect-metadata';
import { randomUUID } from 'crypto';
import assert from 'node:assert/strict';
import dataSource from '../src/database/data-source';
import { SecurityBaseline1791374400000 } from '../src/database/migrations/1791374400000-security-baseline';
import { AppointmentPatientTitle1791380000000 } from '../src/database/migrations/1791380000000-appointment-patient-title';
import { MultiTenant1791390000000, LEGACY_TENANT_ID } from '../src/database/migrations/1791390000000-multi-tenant';
import { Patient } from '../src/patients/patient.entity';
import { Session } from '../src/sessions/session.entity';
import { SessionExercise } from '../src/sessions/session-exercise.entity';
import { Exercise } from '../src/exercises/exercise.entity';
import { PatientsService } from '../src/patients/patients.service';
import { SessionsService } from '../src/sessions/sessions.service';
import { DashboardController } from '../src/dashboard/dashboard.controller';
import { PatientReports1791400000000 } from '../src/database/migrations/1791400000000-patient-reports';
import { PatientReportsService } from '../src/patients/patient-reports.service';
import { PatientReport } from '../src/patients/patient-report.entity';

async function check() {
  await dataSource.initialize();
  const runner = dataSource.createQueryRunner();
  await runner.startTransaction();
  const originalConfirmation = process.env.LEGACY_SINGLE_TENANT_CONFIRMED;
  try {
    const schema = 'tenant_check_' + randomUUID().replaceAll('-', '');
    await runner.query(`CREATE SCHEMA "${schema}"`);
    await runner.query(`SET LOCAL search_path TO "${schema}", public`);
    await new SecurityBaseline1791374400000().up(runner);
    await new AppointmentPatientTitle1791380000000().up(runner);
    const oldUser = randomUUID(), oldPatient = randomUUID();
    await runner.query(`INSERT INTO users(id, name, email, "passwordHash", role) VALUES ($1, 'Synthetic', 'synthetic@invalid.test', 'unusable', 'PHYSIO')`, [oldUser]);
    await runner.query(`INSERT INTO patients(id, "fullName", "medicalRecordNumber", "birthDate") VALUES ($1, 'Synthetic A', 'SYNTHETIC-1', '2000-01-01')`, [oldPatient]);
    await runner.query(`INSERT INTO audit_events("userId", ip, action, resource) VALUES ('synthetic', '127.0.0.1', 'test', 'test')`);
    delete process.env.LEGACY_SINGLE_TENANT_CONFIRMED;
    await assert.rejects(new MultiTenant1791390000000().up(runner), /LEGACY_SINGLE_TENANT_CONFIRMED/);
    process.env.LEGACY_SINGLE_TENANT_CONFIRMED = 'true';
    await new MultiTenant1791390000000().up(runner);
    await new PatientReports1791400000000().up(runner);
    const a = LEGACY_TENANT_ID, b = randomUUID();
    const manager = runner.manager;
    const [{ count }] = await runner.query(`SELECT count(*)::int AS count FROM audit_events WHERE "tenantId" = $1`, [a]);
    assert.equal(count, 1, 'legacy audit backfill');
    await runner.query(`INSERT INTO tenants(id, name) VALUES ($1, 'Synthetic B')`, [b]);
    const patientB = await manager.save(Patient, manager.create(Patient, { tenantId: b, fullName: 'Synthetic B', medicalRecordNumber: 'SYNTHETIC-1', birthDate: '2000-01-01' }));
    const patients = new PatientsService(manager.getRepository(Patient), {} as any);
    assert.deepEqual((await patients.findAll(a)).map(p => p.id), [oldPatient]);
    assert.deepEqual((await patients.search('Synthetic', a)).map(p => p.id), [oldPatient]);
    await assert.rejects(patients.findOne(patientB.id, a), /Paciente não encontrado/);
    await assert.rejects(patients.update(patientB.id, { fullName: 'Changed' }, a), /Paciente não encontrado/);
    await assert.rejects(patients.remove(patientB.id, a), /Paciente não encontrado/);
    const exerciseA = await manager.save(Exercise, manager.create(Exercise, { tenantId: a, title: 'Synthetic A' }));
    const exerciseB = await manager.save(Exercise, manager.create(Exercise, { tenantId: b, title: 'Synthetic B' }));
    const sessions = new SessionsService(manager.getRepository(Session), manager.getRepository(SessionExercise));
    await assert.rejects(sessions.create({ patientId: oldPatient, title: 'Synthetic', exercises: [{ exerciseId: exerciseB.id, sets: 1, reps: '1' }] }, a), /Exercício não encontrado/);
    const template = await sessions.create({ patientId: oldPatient, title: 'Synthetic template', isTemplate: true, recurrenceDays: [1], exercises: [{ exerciseId: exerciseA.id, sets: 1, reps: '1' }] }, a);
    await sessions.create({ patientId: patientB.id, title: 'Synthetic template', isTemplate: true, recurrenceDays: [1], exercises: [{ exerciseId: exerciseB.id, sets: 1, reps: '1' }] }, b);
    assert.equal((await sessions.generateWeekSessions(a)).generated, 1, 'clinic A generation');
    assert.equal((await sessions.generateWeekSessions(a)).generated, 0, 'generation idempotence');
    assert.equal((await sessions.findAll(b)).length, 0);
    await assert.rejects(sessions.findAuthorized(template.id, { role: 'PHYSIO', tenantId: b }), /Sessão não encontrada/);
    await runner.query(`UPDATE patients SET "createdAt" = $1`, [new Date(Date.now() - 60000)]);
    const stats = await new DashboardController(manager.getRepository(Patient), manager.getRepository(Session)).stats({ tenantId: b } as any);
    assert.equal(stats.registeredPatients, 1, 'clinic B dashboard');
    assert.equal(stats.pendingSessions, 0);
    const rejectSql = async (sql: string, params: any[]) => {
      await runner.query('SAVEPOINT boundary_check');
      await assert.rejects(runner.query(sql, params));
      await runner.query('ROLLBACK TO SAVEPOINT boundary_check');
    };
    await rejectSql(`INSERT INTO sessions(title, "tenantId", "patientId") VALUES ('Synthetic', $1, $2)`, [a, patientB.id]);
    await rejectSql(`INSERT INTO session_exercises("sessionId", "exerciseId", sets, reps) VALUES ($1, $2, 1, '1')`, [template.id, exerciseB.id]);
    await rejectSql(`UPDATE patients SET "tenantId" = $1 WHERE id = $2`, [b, oldPatient]);
    await rejectSql(`UPDATE audit_events SET action = 'changed'`, []);
    const progress = new PatientReportsService(manager.getRepository(PatientReport));
    const report = await progress.create(oldPatient, { title: 'Synthetic report', content: '# Synthetic\n\n**Observation**' }, { tenantId: a, userId: oldUser, role: 'PHYSIO' } as any);
    await progress.create(oldPatient, { title: 'Synthetic follow-up', content: 'Second observation' }, { tenantId: a, userId: oldUser, role: 'PHYSIO' } as any);
    const history = await progress.list(oldPatient, a);
    assert.equal(history.reports.length, 2);
    assert.equal(history.reports[0].author.name, 'Synthetic');
    assert.equal(history.reports[0].author.email, undefined);
    await assert.rejects(progress.list(oldPatient, b), /Paciente não encontrado/);
    await assert.rejects(progress.create(patientB.id, { title: 'Synthetic', content: 'Text' }, { tenantId: a, userId: oldUser, role: 'PHYSIO' } as any), /Paciente não encontrado/);
    await rejectSql(`INSERT INTO patient_reports("tenantId", "patientId", "authorId", title, content) VALUES ($1, $2, $3, 'Synthetic', 'Text')`, [b, patientB.id, oldUser]);
    await rejectSql(`UPDATE patient_reports SET content = 'changed' WHERE id = $1`, [report.id]);
    await rejectSql(`DELETE FROM patient_reports WHERE id = $1`, [report.id]);
    console.log('Patient reports: Markdown persistence, multiple reports, author projection, clinic boundaries and history preservation passed.');
    console.log('PostgreSQL: legacy backfill, immutable audit, clinic reads/writes/search, weekly generation, dashboard and cross-tenant constraints passed.');
  } finally {
    if (originalConfirmation === undefined) delete process.env.LEGACY_SINGLE_TENANT_CONFIRMED;
    else process.env.LEGACY_SINGLE_TENANT_CONFIRMED = originalConfirmation;
    await runner.rollbackTransaction();
    await runner.release();
    await dataSource.destroy();
  }
}
check().catch(error => { console.error('Tenant database check failed:', error.message); process.exitCode = 1; });
